parameters:
  _param:
    # MAAS
    infra_postgresql_admin_user_password: OXHvZS908Y4ELR019r6TA8U303J1U45F
    # Do not change below values as needed for prebuilt day01 image
    maas_admin_username: mirantis
    maas_admin_password: gbo7JGIXJisxIdMrwGarMsVgsQmbvmtR
    maas_db_password: ZCcRPAomuXntsuVYhuj1TTPTZMvknUfi
    # StackLight
    alerta_admin_password_generated: uFzIOeDJov5bwGLJUhmO3gmv1wgSHOW4
    grafana_password_generated: K6KOViWG6E2S2x65ctf5OoUnsAeEhCWk
    mysql_grafana_password_generated: 9E14rdNBrW9fhq7Y2y2I00XrRMJqrKNM
    influxdb_stacklight_password_generated: w3JtZQ1N1A6Z4KfhHfFfR0XBAhUo61Hk
    influxdb_admin_password_generated: R3aEWSRA4w5LPOROnbPXpPvJp0EaBJGK
    influxdb_password_generated: yrNeCaeVn6wugNOYSpVj9f2D4SkIY1Wz
    stacklight_log_keepalived_password_generated: hD4ZqWVJrjxwBSoU0Dsyp7Y2TwX1v6hF
    stacklight_telemetry_keepalived_password_generated: zoNDd9CL9470jsmJacoWwqxQGjVOHc2s
    keepalived_stacklight_monitor_vip_password_generated: x4BZAtnLHzUWWY8XEF0wG6Lt38fd2fdU
    keepalived_prometheus_vip_password_generated: yIK6Wf5P3W0M1jZDvio8pPkVdQah7ZhJ
    stacklight_monitor_rabbitmq_password_generated: KPLVBOa94jryCN9f2DuvsjVXK9ajfWQ4
    stacklight_monitor_uchiwa_password_generated: smaLf2JgvPdMPTgFDnO1GrBkD4x10e1Q
    stacklight_monitor_keepalived_password_generated: L00s9HErNsufLr3kdbVm33fsrDSF84NY
    # OpenStack
    horizon_secret_key_generated: 7dn32KYdm2lkrfYBhezPdPULfXllIXGktlkagdzia9hOC19yQzWktOLIqbolwMXH
    keystone_swift_password_generated: WWhGBGKsYhFkbK4OqLBZtOmjbh4GK92w
    rabbitmq_openstack_password_generated: ibZRHLwV55sgyr5TNUKeBbC3vOCcGNsT
    heat_domain_admin_password_generated: Qu529IZVhmLcg0kK2DgxUN1onSLqKQuK
    ceilometer_influxdb_password_generated: MM6yZcSaMfwzSSwycogygIIifldBreyj
    billometer_secret_key_generated: q8dbV2qkInublbCKebNW2w6JNzfztrhtTU99ByCgJdtIKnclHjMb1VZxSOVgP68x
    mysql_aodh_password_generated: PaICk3bRhXMCTM7T2ZGB7NVjk9tmo5by
    mysql_cinder_password_generated: JkIbY9J6uFHcD0mAJtCmq465tQFj5kb7
    mysql_ceilometer_password_generated: N13DK5wNHVTvOQ5XP0Z4fgXrVM2nQvQ7
    mysql_glance_password_generated: FGwaV3nYwOnBqZXi4nfpaNMljiuNnNEH
    mysql_gnocchi_password_generated: y9jBEFW2SLbCLtclEzM2R1nw3i5bnnE2
    mysql_heat_password_generated: sv6tDaxL5knSQZRAn4vjmUfaWQFgLMSg
    mysql_keystone_password_generated: QDKv00wN5otSCW0qDTwtXIDLIdL80L3C
    mysql_neutron_password_generated: kjU8ZdZ5VAxzlKwuVqYCAjRvhvTUAZ5U
    mysql_nova_password_generated: ZTH1nnpkGL6l4gfnrGO20RBGnlC7Va8D
    mysql_panko_password_generated: TJ6mRm5gDaFwRcnsRaHNQpbrXoFzpQHs
    mysql_designate_password_generated: JlwmT3xF2ARWAlXMYugWInE2BP5NSNSu
    keystone_service_token_generated: HoUgdrFBLN9kZOKX
    keystone_admin_password_generated: gZhyiCYldeDXAo9T5SJ9ezHEf6LFzrdP
    keystone_ceilometer_password_generated: s334vMrS8ktlyxSmuASYqdfD2krtELtH
    keystone_cinder_password_generated: JmskZxrNEfozYEyl38Oi7CIrwUTwqFsw
    keystone_glance_password_generated: uLeCJkVU6n9FUZj3diFnV38yUJeOO1pL
    keystone_gnocchi_password_generated: Wvaj9kAoj9lzK0HKjcWyUiyJyal3XvNK
    keystone_heat_password_generated: 7QM7QMX4uRAeLj3NEGhLNb5BjVxFLCQe
    keystone_keystone_password_generated: Bbu5h6ghYacFjnrKZVbEqtcSdpTwaKWC
    keystone_neutron_password_generated: fcmMOP374DVP2f8OIe7kvBN3Ho9B8bi2
    keystone_nova_password_generated: OfmYuWx8ojczUu9CbEJ2WJqrIqqMVWg0
    keystone_aodh_password_generated: RubcrGWp51fkdoaMayyDch704FNuPgtx
    keystone_panko_password_generated: 3UbAJmNCvQkxXW1t9sG7IdI8PKKhTigQ
    keystone_designate_password_generated: mdw7fiDmaJC211wgBJ9i5ba3OgcTnbtr
    ceilometer_secret_key_generated: 7fBIQaFAXJaO7cs7
    mongodb_ceilometer_password_generated: KMXsCAI5EsU3wAqzwL3qgCn40a5l9VaR
    mongodb_admin_password_generated: N73bx9y4ijX5KqnDGex84YBJaNIUuJm3
    mongodb_shared_key_generated: bLiYKem2W4BIKoV85SZBbZKd3dEfSJB2bQFDtCE8YWRBis80JUVdR7g6Kfh0XzRZ
    openstack_metadata_password_generated: dcVxtOOKjEFYmxL9Nif7aoefUELumX9I
    keystone_billometer_password_generated: 6XvuBqHedz9Okh6tVuY7q1aCs09k5K2N
    cinder_storage_secret_uuid_generated: "2ba4dcbe-6a3e-16a7-cc9f-0b2c3cc04969"
    nova_storage_secret_uuid_generated: "42a13e0d-6786-af0e-f492-b8262c300f3e"
    nova_memcache_secret_key_generated: SiWXQJCvuIr4o7eY
    cinder_memcache_secret_key_generated: i25n5a6BCIY1Z1Go
    glance_memcache_secret_key_generated: p33qScnifnooydJ1
    neutron_memcache_secret_key_generated: FrmjMVciSwyVsWEh
    heat_memcache_secret_key_generated: hbITE4ErElUBvAj6
    # Opencontrail
    opencontrail_stats_password_generated: 5AkwLR65T1F3EF8f7kM1Cdmj4tktJ6Tm
    opencontrail_admin_password_generated: G5ANwBgrENRAOPi7gI0TGKjaVq3WA4tl
    opencontrail_redis_password_generated: dSpx6OGkwP47rm7Y7WDDH9tE6WYkaGmH
    # DriveTrain / CICD
    openldap_admin_password_generated: 7CEUVysQ8f8GeyFHgPQ64SKhuWSIMqdp
    openldap_config_password_generated: JIwh6QaOeh80lPf2CE40MXaPCBIlJsbr
    openldap_readonly_password_generated: kdXyCZOpukMoC0c1Rwvd8lvWXSkq4DDQ
    jenkins_admin_password_generated: HVCQ7xZdgGdNxpezYhoYBkYvMhCx9IBz
    gerrit_admin_password_generated: 4Vl59rXkd8xSoTwyAjs6nr00vHlYgvNo
    cicd_keepalived_vip_password_generated: ZNrb8wwiYmSa35BUvI9pEp9ylKwwQNZ2
    cicd_mysql_admin_password_generated: DeV8sXmWUK18osDVs4YWjDgK1IKPaNrw
    cicd_mysql_gerrit_password_generated: OvBZ4uStOF6ZXi87Zt5wUlTg03SuRW7u
    jenkins_admin_public_key_generated: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7cXYj6q/i38v7g3qa7v56YoyYWlXQHRQEjV4vZgJxY8HtF8WBdml6oZJcrLWs2XeSjGJJbJpf4yQ/+l3Cs/kj8U6EdOs8rZYrYviXuec41k4H7VFGLeJOO4+EzXhE/W8LvdoE+KJdL5V/9DjRJUPSO3/BbdgAVH5mbuLELYwiRw5NPXHuxrsxF4vx0rngv9CZmp74OqLnx8kiyAG39pvrzCOpsZsWyVHwuHNiGHvXji5RZqcDtoTRKJTgTAJiqrAytE5zDWPlab5CZOV/93B7tVpI3yxWxoagQE/hqBujonDUJkVukfTh+2bmpvJmMPdEISNXnLj4ForbUDhTH/K3
    jenkins_admin_private_key_generated: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAu3F2I+qv4t/L+4N6mu7+emKMmFpV0B0UBI1eL2YCcWPB7RfF
      gXZpeqGSXKy1rNl3koxiSWyaX+MkP/pdwrP5I/FOhHTrPK2WK2L4l7nnONZOB+1R
      Ri3iTjuPhM14RP1vC73aBPiiXS+Vf/Q40SVD0jt/wW3YAFR+Zm7ixC2MIkcOTT1x
      7sa7MReL8dK54L/QmZqe+Dqi58fJIsgBt/ab68wjqbGbFslR8LhzYhh7144uUWan
      A7aE0SiU4EwCYqqwMrROcw1j5Wm+QmTlf/dwe7VaSN8sVsaGoEBP4agbo6Jw1CZF
      bpH04ftm5qbyZjD3RCEjV5y4+BaK21A4Ux/ytwIDAQABAoIBAAskm5lXAk3CcCXr
      kwZS3t33rdQAyskscVwz6z12Gv8SpxypJRylJXAc2s6XldVIuEsF/XHP+v1oS2di
      QuCoQk9YsQo+yR06VIsPvyeF7bD7THg8K3C4mZN9BvMmI9g2GLvh9WwGO+C+S2zn
      39jPFlERKG8fUI/0de8w+FohOwtug+KznvOkKypZGpZtrbeaf9QVg6cstcidti1S
      Rx26rnJIXYTDmuT7bcYBBkLJTW9IhR+I/i+NVb+Y0hay25SGCR6D8yl8o7bywLzu
      TAU6ldXAQ4DaCs9GBGZD9vJZKw1U84hjv3hLvcvbqeJlYOQ6XqA0vlBJ5AWALb45
      yIXzeUECgYEA46OZhF+eP3Pm7m/UL8vmyl3Q7kYu2v1g2s9VM8RO7CfY5P5pH5kP
      Kha6Kri7OcDEkkMETUno02Qi2lvKiT2dKHTD13yTXbKx8zeaYPV439ri9l4NQ6UC
      MjaUSVRNe4QUE3aojnVp+5+Nwb8RYiYE09ZUfl+jNwmBWxtgeHHLRHMCgYEA0svX
      VbCYh2azLp9qB15tTMQcPL2WOzZk6FgmSojTkXnovphJB85Dsw8qKN8C1C+g1/qI
      WSoQoVTvijAS7u9UH+LtueQXYfRDpCnebjs10lCFCOdNM0CxsKYZjC658SyylDWW
      bipbnUtEyprA+lR1i1d//obxVt4C1n27ymk3S60CgYEA4AQpmVk3tB3tDoxCdd7k
      +hUk/LdYeO2MmQgcQttXB5OXIJM1BIFtqO/AuTYeGZGYYI9O9nhbhVwv6E8Ym8Jk
      nGF8MN1JcJXgBQedBvnKwBD59ZVM3FrQNHX9q8Qok/rAfv7wlXD6oUK9EANlqf7c
      FVQAxnR7fDgAcpYYc68YZ/0CgYBX7ZFH/B7TtAIf+30Vz8yVzePdblOhJWJYDJUE
      WCiwMQLlpc4oxGA266dxXvzmF2vnS2jekI5ZTX2RzdXH9urHVjhFZyBdyq8AZjqT
      Dn232cB0Y08vhtfX0KEteTw0nqlq6yNxlpeaeBAc1wqSIPLbCcepGw7GZlsWr2HK
      37KiDQKBgEnCDGm4zA9ZamjL38XoMMePAVCJbQiLL4EV8oWhqkeXIvDuFAlhSxtN
      tR0gWOj+1ry/jstiCvVFnDY3BPZU6nnW5U1/Yfc5F6oPEyaTzkVDzhPLV07i7ZFU
      w13ISer70jwiUXkzOZ2bbAQu6bOTINIVrAiHv13txqzJQbRMIpFw
      -----END RSA PRIVATE KEY-----
    rabbitmq_admin_password_generated: d0QhYO1nGyUrO1xBAyaUSN1fjOH0AQhX
    rabbitmq_secret_key_generated: tJ0jffN7gLtgIFHx
    galera_server_maintenance_password_generated: KVCkqZwwkuC3WwTRfXcMWOPi5VZO37JH
    galera_server_admin_password_generated: 5l3ZVADtlQgIfnBLtcqIYvZCoMas4Q7d
    galera_server_sst_password_generated: iVmzUt4tO2nZWRl7vnNw4HhSSM7bA0EN
    docker_registry_http_secret_generated: 9eBSFLgeSlRtwOKC
