classes:
- service.cinder.volume.local
- system.cinder.upgrade
- system.salt.minion.cert.mysql.clients.openstack.cinder
- system.salt.minion.cert.rabbitmq.clients.openstack.cinder
parameters:
  cinder:
    volume:
      enabled: True
      database:
        host: ${_param:single_address}
        x509:
          enabled: ${_param:openstack_mysql_x509_enabled}
          ca_file: ${_param:mysql_cinder_ssl_ca_file}
          key_file: ${_param:mysql_cinder_client_ssl_key_file}
          cert_file: ${_param:mysql_cinder_client_ssl_cert_file}
        ssl:
          enabled: ${_param:galera_ssl_enabled}
      glance:
        host: ${_param:single_address}
      barbican:
        enabled: ${_param:barbican_integration_enabled}
      message_queue:
        port: ${_param:openstack_rabbitmq_port}
        host: ${_param:single_address}
        x509:
          enabled: ${_param:openstack_rabbitmq_x509_enabled}
          ca_file: ${_param:rabbitmq_cinder_ssl_ca_file}
          key_file: ${_param:rabbitmq_cinder_client_ssl_key_file}
          cert_file: ${_param:rabbitmq_cinder_client_ssl_cert_file}
        ssl:
          enabled: ${_param:rabbitmq_ssl_enabled}
      identity:
        host: ${_param:single_address}
        region: ${_param:openstack_region}
      cache:
        security:
          enabled: ${_param:cinder_memcache_security_enabled}
          strategy: ${_param:openstack_memcache_security_strategy}
          secret_key: ${_param:cinder_memcache_secret_key}
