classes:
- system.prometheus.gainsight.elasticsearch_container
parameters:
  _param:
    gainsight_elasticsearch_enabled: 'true'
    gainsight_elasticsearch_csv_upload_url: 'http://localhost:9999'
    gainsight_elasticsearch_account_id: 'default'
    gainsight_elasticsearch_environment_id: 'default'
    gainsight_elasticsearch_app_org_id: 'default'
    gainsight_elasticsearch_access_key: 'default'
    gainsight_elasticsearch_job_id: 'default'
    gainsight_elasticsearch_login: 'default'
    gainsight_elasticsearch_elasticsearch_vip: ${_param:stacklight_log_address}
    gainsight_elasticsearch_config_directory: '/srv/gainsight'
    gainsight_elasticsearch_crontab_directory: '/etc/cron.d'
    gainsight_elasticsearch_config_path: "${_param:gainsight_elasticsearch_config_directory}/config.ini"
    gainsight_elasticsearch_csv_retention: 180
  docker:
    client:
      stack:
        monitoring:
          network:
            monitoring:
              driver: overlay
              driver_opts:
                encrypted: 1
          service:
            gainsight_elasticsearch:
              networks:
                - monitoring
              deploy:
                replicas: 1
                labels:
                  com.mirantis.monitoring: "gainsight_elasticsearch"
                restart_policy:
                  condition: any
              labels:
                com.mirantis.monitoring: "gainsight_elasticsearch"
              image: ${_param:docker_image_prometheus_gainsight_elasticsearch}
              volumes:
                - ${prometheus:gainsight_elasticsearch:dir:config}:${_param:gainsight_elasticsearch_config_directory}
                - ${prometheus:gainsight_elasticsearch:dir:crontab}:${_param:gainsight_elasticsearch_crontab_directory}
                - ${prometheus:gainsight_elasticsearch:dir:csv}:/opt/gainsight/csv
              environment:
                CSV_UPLOAD_URL: "${_param:gainsight_elasticsearch_csv_upload_url}"
                ACCOUNT_ID: "${_param:gainsight_elasticsearch_account_id}"
                ENVIRONMENT_ID: "${_param:gainsight_elasticsearch_environment_id}"
                APP_ORG_ID: "${_param:gainsight_elasticsearch_app_org_id}"
                ACCESS_KEY: "${_param:gainsight_elasticsearch_access_key}"
                JOB_ID: "${_param:gainsight_elasticsearch_job_id}"
                LOGIN: "${_param:gainsight_elasticsearch_login}"
                ELASTICSEARCH_HOST: "${_param:gainsight_elasticsearch_elasticsearch_vip}"
                CONFIG_PATH: "${_param:gainsight_elasticsearch_config_path}"
                ENABLED: "${_param:gainsight_elasticsearch_enabled}"
                RETENTION: ${_param:gainsight_elasticsearch_csv_retention}
