parameters:
  prometheus:
    server:
      target:
        static:
          prometheus_federation:
            honor_labels: true
            metrics_path: '/federate'
            scrape_interval: 30s
            scrape_timeout: 30s
            endpoint:
             - address: ${_param:stacklight_monitor_address}
               port: 15010
