classes:
- system.prometheus.server.container
parameters:
  _param:
    kubernetes_prometheus_image: ${_param:mcp_docker_registry}/openstack-docker/prometheus:2018.8.0
    kubernetes_prometheus_enabled: true
    kubernetes_prometheus_server_resources_limits_memory: 1G
    kubernetes_prometheus_server_resources_requests_memory: 1G
  kubernetes:
    common:
      addons:
        prometheus:
          enabled:  ${_param:kubernetes_prometheus_enabled}
          server:
            image: ${_param:kubernetes_prometheus_image}
            bind:
              port: ${prometheus:server:bind:port}
              host: ${prometheus:server:bind:address}
            config:
              config_dir: ${prometheus:server:dir:config_in_container}
              host_config_dir: ${prometheus:server:dir:config}
              data_dir: ${_param:prometheus_server_data_directory}
              host_data_dir: ${prometheus:server:dir:data}
            resources:
              limits:
                memory: ${_param:kubernetes_prometheus_server_resources_limits_memory}
              requests:
                memory: ${_param:kubernetes_prometheus_server_resources_requests_memory}
